#!/bin/bash

# VPS Environment Fix Script
echo "🔧 VPS Environment düzeltme scripti"
echo ""
echo "SSH ile bağlanmak için:"
echo "ssh system141@195.26.249.142"
echo ""
echo "VPS'de çalıştırılacak komutlar:"
echo "================================"
echo ""
echo "# 1. Doğru dizine git:"
echo "cd /home/system141/tesstagain || cd /opt/tesstagain"
echo ""
echo "# 2. Git repository'yi kontrol et:"
echo "git status"
echo "git remote -v"
echo ""
echo "# 3. En son değişiklikleri çek:"
echo "git fetch origin"
echo "git checkout vpstest"
echo "git pull origin vpstest"
echo ""
echo "# 4. .env.local dosyasını manuel düzenle:"
echo "cd frontend"
echo "sudo nano .env.local"
echo ""
echo "# Aşağıdaki satırları ekle/düzenle:"
echo "NEXT_PUBLIC_PINATA_API_KEY=your_actual_pinata_api_key"
echo "NEXT_PUBLIC_PINATA_SECRET_KEY=your_actual_pinata_secret_key"
echo "NEXT_PUBLIC_MARKETPLACE_ADDRESS=0xe553934B8AD246a45785Ea080d53024aAbd39189"
echo ""
echo "# 5. Docker'ı yeniden build et:"
echo "cd .."
echo "sudo docker-compose down"
echo "sudo docker-compose build --no-cache"
echo "sudo docker-compose up -d"
echo ""
echo "# 6. Logları kontrol et:"
echo "sudo docker logs jugiter-frontend"
echo ""
echo "================================"